// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkLt80P9Kr2PWpd5ZhKirHCUMVmS6pFfs',
    appId: '1:171888871474:web:afed330cb029985614d42b',
    messagingSenderId: '171888871474',
    projectId: 'skill-tes-ip',
    authDomain: 'skill-tes-ip.firebaseapp.com',
    storageBucket: 'skill-tes-ip.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUGCLTvNKVdnSA8lJpaiJHkFKQndlX81Q',
    appId: '1:171888871474:android:ccaf0c51797904e414d42b',
    messagingSenderId: '171888871474',
    projectId: 'skill-tes-ip',
    storageBucket: 'skill-tes-ip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABjNBbq0LVCHmD1TB81XHP5kdwRiY2MAI',
    appId: '1:171888871474:ios:d7457a9b6e02345214d42b',
    messagingSenderId: '171888871474',
    projectId: 'skill-tes-ip',
    storageBucket: 'skill-tes-ip.appspot.com',
    iosClientId: '171888871474-9u0lhhnnkjobfos6g25i99bhqd8rebvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABjNBbq0LVCHmD1TB81XHP5kdwRiY2MAI',
    appId: '1:171888871474:ios:d7457a9b6e02345214d42b',
    messagingSenderId: '171888871474',
    projectId: 'skill-tes-ip',
    storageBucket: 'skill-tes-ip.appspot.com',
    iosClientId: '171888871474-9u0lhhnnkjobfos6g25i99bhqd8rebvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
